apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
resources:
  #- helm-release.yaml
  - config-pvc.yaml
configMapGenerator:
  - name: ltb-config
    files:
      - config.inc.local.php
  - name: custom-css
    files:
      - custom.css
  - name: poststart-sh 
    files:
      - postStart.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
