---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: mike@kao.family
  PGADMIN_DEFAULT_PASSWORD: faith6510
  PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: servers-json
  namespace: media
data:
  servers.json: |
    {
      "Servers": {
          "1": {
              "Name": "defaultpg",
              "Group": "Servers",
              "Host": "defaultpg-rw.databases.svc.cluster.local",
              "Port": 5432,
              "MaintenanceDB": "postgres",
              "Username": "postgres",
              "SSLMode": "prefer",
              "SSLCert": "",
              "SSLKey": "",
              "SSLCompression": 0,
              "Timeout": 10,
              "UseSSHTunnel": 0,
              "TunnelPort": "22",
              "TunnelAuthentication": 0
          },
          "2": {
              "Name": "backup",
              "Group": "Servers",
              "Host": "backup-rw.databases.svc.cluster.local",
              "Port": 5432,
              "MaintenanceDB": "postgres",
              "Username": "postgres",
              "SSLMode": "prefer",
              "SSLCert": "",
              "SSLKey": "",
              "SSLCompression": 0,
              "Timeout": 10,
              "UseSSHTunnel": 0,
              "TunnelPort": "22",
              "TunnelAuthentication": 0
          }
      }
    }
