---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-intel-device-plugin-operator
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
resources:
  - app
      #spec:
      #  dependsOn:
      #    - name: cluster-apps-node-feature-discovery
      #  path: ./cluster/apps/kube-tools/intel-device-plugin/app
      #  prune: true
      #  sourceRef:
      #    kind: GitRepository
      #    name: flux-system
      #  healthChecks:
      #    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      #      kind: HelmRelease
      #      name: intel-device-plugin-operator
      #      namespace: kube-tools
      #  interval: 30m
      #  retryInterval: 1m
      #  timeout: 3m
    #---
    ## yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
    #apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    #kind: Kustomization
    #metadata:
    #  name: cluster-apps-intel-device-plugin-gpu
    #  namespace: flux-system
    #  labels:
    #    substitution.flux.home.arpa/enabled: "true"
    #spec:
    #  dependsOn:
    #    - name: cluster-apps-intel-device-plugin-operator
    #  path: ./cluster/apps/kube-tools/intel-device-plugin/gpu
    #  prune: true
    #  sourceRef:
    #    kind: GitRepository
    #    name: flux-system
    #  healthChecks:
    #    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    #      kind: HelmRelease
    #      name: intel-device-plugin-gpu
    #      namespace: kube-tools
    #  interval: 30m
    #  retryInterval: 1m
    #  timeout: 3m
    #---
    ## yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
    #apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    #kind: Kustomization
    #metadata:
    #  name: cluster-apps-intel-device-plugin-gpu-exporter
    #  namespace: flux-system
    #  labels:
    #    substitution.flux.home.arpa/enabled: "true"
    #spec:
    #  dependsOn:
    #    - name: cluster-apps-intel-device-plugin-gpu
    #  path: ./cluster/apps/kube-tools/intel-device-plugin/exporter
    #  prune: true
    #  sourceRef:
    #    kind: GitRepository
    #    name: flux-system
    #  healthChecks:
    #    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    #      kind: HelmRelease
    #      name: intel-gpu-exporter
    #      namespace: kube-tools
    #  interval: 30m
    #  retryInterval: 1m
    #  timeout: 3m
