apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #  - ./kube-prometheus-stack
 - ./monitoring-config
 - ./certificates
 - ./serviceaccounts
 - ./oauth2-oidc-debugger

#patchesStrategicMerge:
#  - prometheus-op-values.yaml
