---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-monitoring-grafana
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-databases-postgres-clusters
  path: ./cluster/staging/apps/monitoring/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kube-grafana
      namespace: monitoring 
  interval: 30m
  wait: true
  retryInterval: 1m
  timeout: 3m
---
