apiVersion: apps/v1
kind: Deployment
metadata:
  name: doesNotMatter
  namespace: networking
spec:
  template:
    spec:
      initContainers:
        name: init-db
        image: ghcr.io/onedr0p/postgres-initdb:14.5
        env:
          - name: POSTGRES_HOST
            value: defaultpg-rw.databases.svc.cluster.local
          - name: POSTGRES_DB
            value: authelia
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
                namespace: databases
          - name: POSTGRES_USER
            value: authelia
          - name: POSTGRES_PASS
            value: authelia

