apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  # renovate: registryUrl=https://metallb.github.io/metallb chart=metallb
  - github.com/metallb/metallb//config/crd?ref=metallb-chart-0.13.5
  - helm-release.yaml
  - ipaddresspools.yaml
