---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mm-config-js
  namespace: media
data:
  config.js: |
    let config = {
    	address: "0.0.0.0",
    	port: 8080
    	basePath: "/",
    	ipWhitelist: [],
    	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
    	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
    	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true
        language: "en",
        locale: "en-US",
        logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
        timeFormat: 24,
        units: "metric",
        modules: [
          {
            module: "alert",
          },
          {
            module: "updatenotification",
            position: "top_bar"
          },
          {
            module: "clock",
            position: "top_left"
          },
          {
            module: "calendar",
            header: "US Holidays",
            position: "top_left",
            config: {
              calendars: [
                {
                  symbol: "calendar-check",
                  url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"                   }
              ]
            }
          },
          {
            module: "compliments",
            position: "lower_third"
          },
          {
            module: "weather",
            position: "top_right",
            config: {
              weatherProvider: "openweathermap",
              type: "current",
              location: "New York",
              locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
              apiKey: "YOUR_OPENWEATHER_API_KEY"
            }
          },
          {
            module: "weather",
            position: "top_right",
            header: "Weather Forecast",
            config: {
              weatherProvider: "openweathermap",
              type: "forecast",
              location: "New York",
              locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
              apiKey: "YOUR_OPENWEATHER_API_KEY"
            }
          },
          {
            module: "newsfeed",
            position: "bottom_bar",
            config: {
              feeds: [
                {
                  title: "NPR",
                  url: "https://feeds.npr.org/"
                }
              ],
              showSourceTitle: true,
              showPublishDate: true,
              broadcastNewsFeeds: true,
              broadcastNewsUpdates: true
            }
          },
        ]
    };
    
    /*************** DO NOT EDIT THE LINE BELOW ***************/
    if (typeof module !== "undefined") {module.exports = config;}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: magicmirror-install-modules
data:
  install_modules.sh: |-
    cd /opt/magic_mirror/modules
    {{ range $index, $val := .Values.modules.install }}
    echo installig {{ $val | quote }}
    git clone {{ $val | quote }}
    folder=$(echo {{ $val | quote }} | sed -r 's|.*\/(.*)|\1|g' | xargs)
    cd $folder
    npm install --omit=dev || true
    cd ..
    {{ end }}
    ls -la
