apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - ingress.yaml
  - secret.sops.yaml
    #patchesStrategicMerge:
    #  - config/patch-postgres.yaml
patches:
  - path: config/patch-deployment.yaml
    target:
      kind: Deployment
      name: "*.*"
