---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: go-skynet-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://go-skynet.github.io/helm-charts/
  timeout: 3m
