---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-at-home
  namespace: flux-system
spec:
  interval: 30m
  url: https://k8s-at-home.com/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://bjw-s.github.io/helm-charts/
---


